name: build
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Build"
      uses: muinmomin/webhook-action@v1.0.0
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        data: '{"key":"SECRETAPPKEY", "mode": "build", "owner": "${{ github.repository_owner }}", "repository":"Com.Sibz.NetCode", "args":{}, "clean": "false", "context":"remote test", "sha": "${{ github.sha }}"}'